version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: advertise-ai
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  pgvector:
    image: pgvector/pgvector:pg16
    depends_on:
      - postgres
    environment:
      PGVECTOR_DB: your_db
      PGVECTOR_USER: your_user
      PGVECTOR_PASSWORD: your_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
    driver: local